variables:
  - &platforms 'linux/arm/v7,linux/arm64/v8,linux/amd64'
  - &docker_creds
    username:
      from_secret: guisea_docker_user
    password:
      from_secret: guisea_docker_password

pipeline:
  ###############
  # S e r v e r #
  ###############

  publish-server:
    image: woodpeckerci/plugin-docker-buildx
    group: docker
    settings:
      <<: *docker_creds
      repo: guisea/pg_dump
      dockerfile: Dockerfile
      platforms: *platforms
      tag: "latest"
    when:
      branch: ${CI_REPO_DEFAULT_BRANCH}
      event: push

  publish-server-tagged:
    group: docker
    image: woodpeckerci/plugin-docker-buildx
    settings:
      <<: *docker_creds
      repo: guisea/pg_dump
      dockerfile: Dockerfile
      platforms: *platforms
      tags: ["latest", "${CI_COMMIT_TAG}"]
    when:
      event: tag