depends_on:
  - build

# Clone is not needed as Docker image built in previous stage
skip_clone: true

pipeline:
  update-swarm-service-portainer:
    image: docker.io/plugins/webhook
    settings:
      urls: 
        from_secret: deploy_url
      method: POST